#!/usr/bin/env python3
# Converts the .pal files in this folder into nes_palettes.cpp, the selectable
# NES palettes of the settings menu.
#
# A .pal file is 64 RGB888 triplets (192 bytes). The tables are written as
# CC(0xRRGGBB) and CC() packs them at compile time into the format the video
# back-end draws: RGB444 for picoDVI, RGB555 for HSTX.
#
# Usage: python3 assets/Palettes/pal2c.py   (from the repository root or this folder)
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(HERE, "..", "..", "nes_palettes.cpp")

# Width of the settings menu when its overscan option blanks the side columns,
# and the number of rows the description box has.
MENU_COLS = 38
MENU_ROWS = 4
MAX_NAME = 22  # "NES Palette: " + name must fit MENU_COLS

# (menu name, .pal file, description). Index 0 is the palette a board used before
# palettes became selectable; it differs per video back-end, so it names two files.
# Default DVI.pal is the original InfoNES table, expanded from RGB555, except that
# $2D and $3D are greys as on a real 2C02 (InfoNES had them black, which made the
# dimmed text in Bio Hazard's menu vanish). Only $0D/$1D and the $xE/$xF columns are black.
PALETTES = [
    ("Default", ("Default DVI.pal", "Default HSTX.pal"),
     "The palette used by all earlier versions of this emulator on this board."),
    ("Composite Direct (FBX)", "Composite Direct (FBX).pal",
     "Direct capture of the NES composite signal. Capture devices clip some extreme "
     "colors to a different hue: the Super Mario Bros. sky looks purplish."),
    ("NES Classic (FBX)", "NES Classic (FBX).pal",
     "Colors captured over HDMI from the NES Classic Edition that Nintendo released in 2016."),
    ("PC-10", "PC-10.pal",
     "RGB values taken from the original PlayChoice-10 arcade PPU chips."),
    ("PVM Style D93 (FBX)", "PVM Style D93 (FBX).pal",
     "Approximates how an NTSC NES looks on a Sony PVM monitor running at D93 color temperature."),
    ("Smooth (FBX)", "Smooth (FBX).pal",
     "FirebrandX's final NTSC palette: measured NES output levels, slightly tweaked for "
     "digital displays. Wide dark-to-light range."),
    ("Sony CXA", "Sony CXA.pal",
     "Approximates the RGB decoding of NTSC by certain consumer Sony TV sets. "
     "Original author unknown."),
    ("Wavebeam", "Wavebeam.pal",
     "Nakedarthur's approximation of NES colors on consumer NTSC TVs. A more saturated "
     "version of Smooth (FBX)."),
    ("LCD/OLED Balanced", "LCD-OLED Balanced.pal",
     "Reduced saturation for LCD and OLED screens. Contributed by dragonkn9 in issue #256."),
]


def read_pal(name):
    with open(os.path.join(HERE, name), "rb") as f:
        data = f.read()
    if len(data) != 192:
        sys.exit(f"{name}: expected 192 bytes (64 RGB triplets), got {len(data)}")
    return [(data[i] << 16) | (data[i + 1] << 8) | data[i + 2] for i in range(0, 192, 3)]


def menu_rows(text, cols):
    # Same word wrap as putText(..., wraplines=true) in pico_shared/menu.cpp: a word
    # that does not fit starts a new row, and the single space after a word wraps
    # when it reaches the last column.
    x, y = 0, 0
    words = text.split()
    for n, word in enumerate(words):
        if x + len(word) > cols and x != 0:
            x, y = 0, y + 1
        x += len(word)
        if n < len(words) - 1:
            x += 1
            if x >= cols:
                x, y = 0, y + 1
    return y + 1


def table(rgb, indent):
    lines = []
    for row in range(0, 64, 4):
        lines.append(indent + ", ".join(f"CC(0x{c:06X})" for c in rgb[row:row + 4]) + ",")
    return "\n".join(lines)


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    for name, _, desc in PALETTES:
        if len(name) > MAX_NAME:
            sys.exit(f"Name too long for the menu: {name}")
        if "_" in desc or "_" in name:
            sys.exit(f"putText draws '_' as a space: {name}")
        if menu_rows(desc, MENU_COLS) > MENU_ROWS:
            sys.exit(f"Description of {name} needs more than {MENU_ROWS} rows")
    # InfoNES_RefreshPalTable() tells a palette entry the game has not written yet
    # (still 0) from a written index 0 by the color: $00 must not pack to 0.
    for name, files, _ in PALETTES:
        for f in files if isinstance(files, tuple) else (files,):
            c = read_pal(f)[0]
            if not (c & 0xF0F0F0) or not (c & 0xF8F8F8):
                sys.exit(f"{f}: color $00 is black after packing, see InfoNES_RefreshPalTable()")

    out = []
    out.append("// Generated by assets/Palettes/pal2c.py from assets/Palettes/*.pal - do not edit.")
    out.append("#include \"nes_palettes.h\"")
    out.append("")
    out.append("// RGB888 to the format the video back-end draws.")
    out.append("#if !HSTX")
    out.append("#define CC(c) ((((c) >> 4) & 0xF) | ((((c) >> 12) & 0xF) << 4) | ((((c) >> 20) & 0xF) << 8))  // RGB444")
    out.append("#else")
    out.append("#define CC(c) ((((c) & 0xF8) >> 3) | (((c) & 0xF800) >> 6) | (((c) & 0xF80000) >> 9))      // RGB555")
    out.append("#endif")
    out.append("")
    out.append(f"static_assert(NES_PALETTE_COUNT == {len(PALETTES)}, \"NES_PALETTE_COUNT does not match the generated tables\");")
    out.append("")
    out.append("// Kept in flash; the selected one is copied to NesPalette[] in SRAM.")
    out.append("const WORD NesPaletteTables[NES_PALETTE_COUNT][64] = {")
    for name, files, _ in PALETTES:
        out.append(f"    // {name}")
        if isinstance(files, tuple):
            dvi, hstx = files
            out.append("#if !HSTX")
            out.append(f"    {{   // {dvi}")
            out.append(table(read_pal(dvi), "        "))
            out.append("    },")
            out.append("#else")
            out.append(f"    {{   // {hstx}")
            out.append(table(read_pal(hstx), "        "))
            out.append("    },")
            out.append("#endif")
        else:
            out.append(f"    {{   // {files}")
            out.append(table(read_pal(files), "        "))
            out.append("    },")
    out.append("};")
    out.append("")
    out.append("const char *const NesPaletteNames[NES_PALETTE_COUNT] = {")
    for name, _, _ in PALETTES:
        out.append(f"    {c_string(name)},")
    out.append("};")
    out.append("")
    out.append("// Shown below the settings menu while the palette option is highlighted.")
    out.append("const char *const NesPaletteDescriptions[NES_PALETTE_COUNT] = {")
    for _, _, desc in PALETTES:
        out.append(f"    {c_string(desc)},")
    out.append("};")
    out.append("")

    with open(OUTPUT, "w", newline="\n") as f:
        f.write("\n".join(out))
    print(f"Wrote {os.path.normpath(OUTPUT)} ({len(PALETTES)} palettes)")


if __name__ == "__main__":
    main()
